### ISSUE TITLE
No license has been defined for the library in pypi

### ISSUE THREAD

**Issue by davidtam** [DataDog/envier#33]
My company requires license information to be published together with the code in PYPI so that we could use this package.
At the moment it seem like no license information has been published?
Can this be fixed?

I dont actually use this package directly but I use datadog-lambda

Thank you in advance!

**Comment by ZStriker19** [comment]
Hi @davidtam  thanks for reaching out, looking into why the license isn't being added.

**Comment by ZStriker19** [comment]
I think we may've been specifying the license in our pyproject.toml incorrectly. Put up this PR to fix it. https://github.com/DataDog/envier/pull/34
